name: List files changed as GitHub comment

on:
  pull_request
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: Get list of files changed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v4.2
        
      - name: Format changed files
        run: |
          for file in "${{ steps.changed_files.outputs.all_modified_files }}"; do
            file = "$file\n"
          done
        
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Files changed:
            ${{ steps.changed_files.outputs.all_modified_files }}
