name: List files changed as GitHub comment

on:
  pull_request
      
jobs:
  test:
    runs-on: ubuntu-latest
    name: Get list of files changed
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          
      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v4.2
        with:
          separator: ","
          
      - id: get-comment-body
        run: |
          body=${{ steps.changed_files.outputs.all_modified_files }}
          body="${body//,/$'\n'}"
          body="${body//$'\n'/'%0A'}"
          echo ::set-output name=body::$body
        
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
#          body: |
#            ${{ steps.changed_files.outputs.all_modified_files }}
